// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

// 自己测试的玩家用户实体对象
type Player struct {
	// 玩家ID
	ID string `json:"id"`
	// 玩家名字
	Name string `json:"name"`
	// 玩家年龄
	Age *int64 `json:"age"`
}

// 用户注册入参实体对象
type RegisterUser struct {
	// 注册用户名字
	Name string `json:"name"`
	// 注册用户年龄
	Age int64 `json:"age"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
